[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
jaja = "6ar36VKC4QFyx3avJmBFg4C3121Yxu3mmTebbiJ3ASYU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
